"""Generate docs/guide/config-reference.md from the Config field metadata.

    python scripts/gen_config_reference.py            # (re)write the reference
    python scripts/gen_config_reference.py --check    # exit 1 when the committed file is stale

Every row comes from ``Config.field_specs()`` (src/neural_trade/core/config.py): group, name,
default, unit, range or choices, tunable, deprecated and doc. Never edit the reference by hand;
change the metadata and re-run this script (tests/test_config_metadata.py fails on a stale file).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "guide" / "config-reference.md"


def _config_module():
    sys.path.insert(0, str(REPO / "src"))
    from neural_trade.core import config

    return config


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _default(spec) -> str:
    return "`" + _cell(json.dumps(spec.default)) + "`"


def render() -> str:
    """The reference as markdown text (deterministic: the same metadata gives the same bytes)."""
    config = _config_module()
    specs = config.Config.field_specs()
    by_group = {g: [] for g in config.GROUPS}
    for spec in specs.values():
        by_group.setdefault(spec.group, []).append(spec)
    n_tunable = sum(s.tunable for s in specs.values())
    n_deprecated = sum(s.deprecated for s in specs.values())
    lines = [
        "# Config reference",
        "",
        "<!-- Generated by scripts/gen_config_reference.py from the field metadata in",
        "     src/neural_trade/core/config.py. Do not edit by hand: change the metadata and re-run the script. -->",
        "",
        f"Every field of `neural_trade.core.config.Config`: {len(specs)} fields, {n_tunable} tunable, "
        f"{n_deprecated} deprecated. Keys are flat (`configs/default.yaml`, `--set KEY=VALUE`). "
        "`Config.validate` refuses a value outside its range or choices; a range on a list or mapping "
        "applies to each number in it. **Tunable** marks what a sweep may search; **deprecated** marks a "
        "legacy field kept so old config files still load. Registry keys are checked against the "
        "registries when they load (`registries.load_all`), not here.",
        "",
        "## Units",
        "",
        "| unit | meaning |",
        "|---|---|",
    ]
    lines += [f"| `{u}` | {_cell(meaning)} |" for u, meaning in config.UNITS.items()]
    for group, group_specs in by_group.items():
        if not group_specs:
            continue
        lines += ["", f"## {group}", "",
                  "| name | default | unit | range or choices | tunable | deprecated | doc |",
                  "|---|---|---|---|---|---|---|"]
        for s in group_specs:
            rng = s.range_text()
            if rng and s.log:
                rng += " (log scale)"
            if s.nullable:
                rng = (rng + "; " if rng else "") + "null allowed"
            lines.append(f"| `{s.name}` | {_default(s)} | {s.unit} | {_cell(rng)} | "
                         f"{'yes' if s.tunable else 'no'} | {'yes' if s.deprecated else 'no'} | {_cell(s.doc)} |")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when the committed reference is stale")
    args = ap.parse_args(argv)
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if current != text:
            sys.stderr.write(f"{OUT.relative_to(REPO)} is stale: run python scripts/gen_config_reference.py\n")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    sys.stdout.write(f"wrote {OUT.relative_to(REPO)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
