"""Regenerate TESTING_DOCUMENTATION.md from the test suite itself (plan C6).

    python scripts/test_inventory.py            # writes TESTING_DOCUMENTATION.md

The document lists what exists - files, test counts, markers, each module's stated purpose -
and how to run it. It deliberately states no pass/fail results: those come from a pytest run
(CI), never from a hand-written file.
"""
from __future__ import annotations

import ast
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
MARKERS = ("tf", "slow", "gpu", "data", "notebook")


class _Collector:
    def __init__(self):
        self.items = []

    def pytest_collection_modifyitems(self, items):
        self.items = [(i.nodeid, {m.name for m in i.iter_markers()}) for i in items]


def _purpose(path: Path) -> str:
    doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    return " ".join(doc.strip().split("\n\n")[0].split())


def main() -> int:
    sys.path.insert(0, str(REPO / "scripts"))
    from check_coverage import GATES

    col = _Collector()
    code = pytest.main(["--collect-only", "-q", "-p", "no:cacheprovider", str(REPO / "tests")], plugins=[col])
    if code not in (0, 5):
        return int(code)
    by_file = defaultdict(list)
    for nodeid, marks in col.items:
        by_file[nodeid.split("::")[0]].append(marks)
    total = Counter()
    rows = []
    for f in sorted(by_file):
        marks = by_file[f]
        counts = Counter(m for ms in marks for m in ms if m in MARKERS)
        total.update(counts)
        tags = ", ".join(f"{m} {counts[m]}" for m in MARKERS if counts[m])
        rows.append(f"| `{f}` | {len(marks)} | {tags} | {_purpose(REPO / f)} |")
    L = [
        "# Test suite", "",
        "_Generated by `scripts/test_inventory.py` from the collected suite - do not edit by hand._", "",
        f"{len(col.items)} tests in {len(by_file)} files. Markers: " +
        ", ".join(f"`{m}` {total[m]}" for m in MARKERS) + ".", "",
        "## Running", "",
        "```bash",
        'pytest -m "not slow"                  # fast suite (CPU, ~2 min)',
        "pytest -m slow                        # end-to-end training, CLI, notebooks, reproducibility",
        "pytest --cov=neural_trade --cov-report=json:coverage.json && python scripts/check_coverage.py coverage.json",
        "python scripts/golden_run.py verify <oracle.npz>   # a refactor changed no numbers",
        "```", "",
        "Markers: `tf` imports TensorFlow (added automatically); `slow` trains a model or takes more than ~30 s; "
        "`gpu` needs a GPU; `data` reads the bundled CSV; `notebook` executes notebooks (needs ipykernel).", "",
        "## Coverage gates (line coverage per package, `scripts/check_coverage.py`)", "",
        "| package | gate |", "|---|---|",
        *[f"| `{k}` | {v}% |" for k, v in sorted(GATES.items())], "",
        "## Files", "",
        "| file | tests | markers | purpose |", "|---|---|---|---|", *rows, "",
    ]
    (REPO / "TESTING_DOCUMENTATION.md").write_text("\n".join(L), encoding="utf-8")
    print(f"TESTING_DOCUMENTATION.md: {len(col.items)} tests, {len(by_file)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
